# Generated by Django 5.2.1 on 2025-06-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(max_length=20, verbose_name='Tipo de Documento')),
                ('no_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('genero', models.CharField(max_length=20, verbose_name='Género')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('numero', models.CharField(max_length=20, verbose_name='Número de Contacto')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaSubida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='facturas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_subidas', to='asistencia.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='asistencia.persona')),
            ],
        ),
    ]
