# Generated by Django 5.2.1 on 2025-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasubida',
            name='monto',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
