# Generated by Django 5.2.1 on 2025-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_persona_facturasubida_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasubida',
            name='categoria',
            field=models.CharField(default='Otros', max_length=50),
        ),
        migrations.AddField(
            model_name='facturasubida',
            name='fecha',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='facturasubida',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facturasubida',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='facturasubida',
            name='numero',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='facturasubida',
            name='tipo_monto',
            field=models.CharField(choices=[('neto', 'Neto'), ('total', 'Total')], default='neto', max_length=10),
        ),
        migrations.AlterField(
            model_name='facturasubida',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
