# Generated by Django 5.2.1 on 2025-07-07 18:02

import asistencia.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_usuario_rol_notification'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', asistencia.models.UsuarioManager()),
            ],
        ),
    ]
