# Generated by Django 5.2.1 on 2025-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasubida',
            name='factus_pdf_url',
            field=models.URLField(blank=True, help_text='URL del PDF generado por Factus', null=True),
        ),
    ]
