# Generated by Django 5.2.1 on 2025-07-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_facturasubida_factus_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasubida',
            name='factus_public_url',
            field=models.URLField(blank=True, help_text='URL pública de visualización de la factura en Factus', null=True),
        ),
    ]
