# Generated by Django 5.2.1 on 2025-05-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('foto', models.ImageField(null=True, upload_to='fotos/', verbose_name='Foto')),
                ('clase', models.TextField(null=True, verbose_name='Clase')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('fechaIngreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
            ],
        ),
    ]
